name: Hourly Fibonacci Reversal Monitor

on:
  schedule:
    - cron: '15 3-10 * * 1-5'  # Runs hourly from 8:15 AM to 3:15 PM IST (Mon–Fri)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Install Dependencies
        run: |
          pip install -U pip
          pip install pandas numpy yfinance requests papermill

      - name: 🧠 Run Fibonacci Reversal Notebook
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          papermill "Fibonacci_Jackpot_Reversal_Detector_MultiStock_v3.ipynb" "output.ipynb"
