name: Bollinger Band Reversal Bot

on:
  schedule:
    - cron: '*/15 3-10 * * 1-5'  # Every 15 min from 8:30 AM to 3:30 PM IST (03:00–10:00 UTC)
  workflow_dispatch:

jobs:
  bollinger-signals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas numpy yfinance ta tqdm requests

    - name: Run Bollinger Reversal Script
      run: python generate_bollinger_reversal_data.py

    - name: Send Telegram Alerts
      if: success()
      run: |
        import pandas as pd
        import requests
        import os

        file = 'bollinger_reversal_data.csv'
        if not os.path.exists(file):
            print("No data file found. Skipping alert.")
            exit(0)

        df = pd.read_csv(file)
        if df.empty:
            print("No signals to alert.")
            exit(0)

        token = '${{ secrets.TELEGRAM_BOT_TOKEN }}'
        chat_id = '${{ secrets.TELEGRAM_CHAT_ID }}'

        for _, row in df.iterrows():
            msg = (
                f"🔔 *{row['Symbol']}* - *{row['SignalType']} Reversal*\\n"
                f"📅 {row['Date']}\\n"
                f"💰 Close: {row['Close']:.2f}\\n"
                f"📊 RSI: {row['RSI']:.1f}, MACD Diff: {row['MACD_DIFF']:.2f}"
            )
            requests.post(
              f'https://api.telegram.org/bot{token}/sendMessage',
              data={'chat_id': chat_id, 'text': msg, 'parse_mode': 'Markdown'}
            )
      shell: python

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bollinger_reversal_data
        path: bollinger_reversal_data.csv
